### ISSUE TITLE
Nintendo Switch SDL2

### ISSUE THREAD

**Issue by FatherOfEgg** [jakibaki/prepatch#1]
For one, I know this is in a totally different repository, but your ones involving the Nintendo Switch did not have an issue section. Well if you don't mind me asking this here, every time I try to run make, I get something along the lines of "linking gdkGBA-master.elf
C:/devkitPro/portlibs/switch/lib\libSDL2.a(SDL_systhread.o): In function `SDL_ThreadID':
/home/davem/projects/devkitpro/pacman-packages/switch/SDL2/src/SDL2-2.0.8/src/thread/switch/SDL_systhread.c:66: undefined reference to `svcGetThreadId'", this happened a few more times for others similar to this. Then near the end I get this one, "collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:52: /gdkGBA-master/gdkGBA-master.elf] Error 1
make: *** [Makefile:151: build] Error 2". Sorry for bothering you in a way that was not as convenient.

**Comment by jakibaki** [comment]
Sorry, I don't have access to a windows-computer so I can't help you with this :/
